Debug/arm_pru_sharedmem_pru1.object: arm_pru_sharedmem_pru1.c
Debug/arm_pru_sharedmem_pru1.object: /usr/share/ti/cgt-pru/include/stdint.h
Debug/arm_pru_sharedmem_pru1.object: /usr/share/ti/cgt-pru/include/stdio.h
Debug/arm_pru_sharedmem_pru1.object: /usr/share/ti/cgt-pru/include/linkage.h
Debug/arm_pru_sharedmem_pru1.object: /usr/share/ti/cgt-pru/include/stdarg.h
Debug/arm_pru_sharedmem_pru1.object: /usr/lib/ti/pru-software-support-package/include/am335x/pru_cfg.h
Debug/arm_pru_sharedmem_pru1.object: /usr/lib/ti/pru-software-support-package/include/am335x/pru_intc.h
Debug/arm_pru_sharedmem_pru1.object: /usr/lib/ti/pru-software-support-package/include/rsc_types.h
Debug/arm_pru_sharedmem_pru1.object: /usr/lib/ti/pru-software-support-package/include/pru_types.h
Debug/arm_pru_sharedmem_pru1.object: /usr/lib/ti/pru-software-support-package/include/pru_rpmsg.h
Debug/arm_pru_sharedmem_pru1.object: /usr/lib/ti/pru-software-support-package/include/pru_virtqueue.h
Debug/arm_pru_sharedmem_pru1.object: /usr/lib/ti/pru-software-support-package/include/pru_virtio_ring.h
Debug/arm_pru_sharedmem_pru1.object: /usr/share/ti/cgt-pru/include/string.h
Debug/arm_pru_sharedmem_pru1.object: /usr/share/ti/cgt-pru/include/stdlib.h
Debug/arm_pru_sharedmem_pru1.object: /usr/share/ti/cgt-pru/include/math.h
Debug/arm_pru_sharedmem_pru1.object: /usr/share/ti/cgt-pru/include/elfnames.h
Debug/arm_pru_sharedmem_pru1.object: /usr/share/ti/cgt-pru/include/mathf.h
Debug/arm_pru_sharedmem_pru1.object: /usr/share/ti/cgt-pru/include/float.h
Debug/arm_pru_sharedmem_pru1.object: /usr/share/ti/cgt-pru/include/mathl.h
Debug/arm_pru_sharedmem_pru1.object: resource_table_1.h
Debug/arm_pru_sharedmem_pru1.object: /usr/share/ti/cgt-pru/include/stddef.h
Debug/arm_pru_sharedmem_pru1.object: /usr/lib/ti/pru-software-support-package/include/pru_virtio_ids.h
Debug/arm_pru_sharedmem_pru1.object: arm_pru_common.h
Debug/arm_pru_sharedmem_pru1.object: ../../mylibs/libpru/pru_gpo_ct.h
